#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
WORKDIR "/src/src/SolarniBaron.Api"
RUN dotnet build "SolarniBaron.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SolarniBaron.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final

RUN apk add --no-cache tzdata

WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SolarniBaron.Api.dll"]